title: Jekyll DXD Workshop
author: Natali Nascimento
email: natali@nascimento.com
description: > # this means to ignore newlines until "exclude"
  How jekyll works

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  twitter: danielfdsilva
  github:  danielfdsilva
  # facebook:
