title: Portfólio Natali Nascimento
author: Natali Nascimento
email: nascimento.do.nascimento@gmail.com
description: > # this means to ignore newlines until "exclude"
 Portfolio Natali Nascimento, work in progress
baseurl:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"
